-- liquibase formatted sql
-- changeset author:mvl, dbms:PostgreSQL

-- ПОЛЬЗОВАТЕЛИ
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE public.users
(
    id bigint PRIMARY KEY /*GENERATED BY DEFAULT AS IDENTITY*/,
    user_name varchar(100) NOT NULL,
    first_name varchar(255) NOT NULL,
    middle_name varchar(255),
    last_name varchar(255) NOT NULL,
    title varchar(100),
    birth_date date,
    sex varchar(1) CHECK (sex IN ('M','F')),
    avatar_id bigint,
    status varchar(1000),
    registration_date timestamp NOT NULL,
    deleted boolean DEFAULT FALSE NOT NULL,
    version bigint
);
-- Для не удалённых пользователей имена уникальны без учера регистра
CREATE UNIQUE INDEX ixu_username ON public.users (UPPER(TRIM(user_name))) WHERE deleted = FALSE;
CREATE INDEX ixu_user_deleted ON public.users (deleted);

COMMENT ON TABLE public.users is 'Основная информация пользователя.';
COMMENT ON COLUMN public.users.id is 'Уникальный идентификатор пользователя. Автогенерируемый.';
COMMENT ON COLUMN public.users.user_name is 'Имя пользователя (логин). Уникальное без учета регистра.';
COMMENT ON COLUMN public.users.first_name is 'Имя.';
COMMENT ON COLUMN public.users.middle_name is 'Отчество.';
COMMENT ON COLUMN public.users.last_name is 'Фамилия.';
COMMENT ON COLUMN public.users.title is 'Обращение (г-н, г-жа, и т.п.).';
COMMENT ON COLUMN public.users.birth_date is 'День рождения.';
COMMENT ON COLUMN public.users.sex is 'Пол (М(ALE), F(EMALE)).';
COMMENT ON COLUMN public.users.avatar_id is 'ID картинки с аватаром в хранилище S3 (другой сервис).';
COMMENT ON COLUMN public.users.status is 'Текстовое описание, которое задает сам пользователь для совего текущего состояния/настроения.';
COMMENT ON COLUMN public.users.registration_date is 'Дата регистрации пользователя в системе.';
COMMENT ON COLUMN public.users.deleted is 'Признак soft delete.';
COMMENT ON COLUMN public.users.version is 'Версия строки. Для оптимистической блокировки.';

-- rollback DROP TABLE IF EXISTS public.users CASCADE;
