-- liquibase formatted sql
-- changeset author:mvl, dbms:PostgreSQL

-- КОНТАКТЫ ПОЛЬЗОВАТЕЛЕЙ
DROP TABLE IF EXISTS public.user_contacts;
CREATE TABLE public.user_contacts
(
    id bigint PRIMARY KEY /*GENERATED BY DEFAULT AS IDENTITY*/,
    user_id bigint NOT NULL REFERENCES public.users(id) /*ON DELETE CASCADE будем делать это через JPA иначе может быть неконсистентность данных*/,
    kind varchar(50) NOT NULL CHECK (kind IN ('PHONE','EMAIL')),
    value varchar(100) NOT NULL,
    preferred boolean,
    deleted boolean DEFAULT FALSE NOT NULL,
    version bigint
);
CREATE UNIQUE INDEX ixu_user_contacts ON public.user_contacts (user_id, kind, UPPER(TRIM(value))) WHERE deleted = FALSE;

COMMENT ON TABLE public.user_contacts is 'Варианты комуникации с пользователем.';
COMMENT ON COLUMN public.user_contacts.id is 'Уникальный идентификатор. Автогенерируемый.';
COMMENT ON COLUMN public.user_contacts.user_id is 'Идентификатор пользователя. Ссылка на users.id.';
COMMENT ON COLUMN public.user_contacts.kind is 'Тип контакта. PHONE, EMAIL';
COMMENT ON COLUMN public.user_contacts.value is 'Номер телефона, адрес E-Mail и т.п.';
COMMENT ON COLUMN public.user_contacts.preferred is 'Данный метод коммуникации является предпочтительным для пользователя.';
COMMENT ON COLUMN public.user_contacts.deleted is 'Признак soft delete.';
COMMENT ON COLUMN public.user_contacts.version is 'Версия строки. Для оптимистической блокировки.';

-- rollback DROP TABLE IF EXISTS public.user_contacts;