-- liquibase formatted sql
-- changeset author:mvl, dbms:PostgreSQL

-- ЛЮБАЯ ДОП.ИНФОРМАЦИЯ ПОЛЬЗОВАТЕЛЕЙ
DROP TABLE IF EXISTS public.user_add_info;
CREATE TABLE public.user_add_info
(
    id bigint PRIMARY KEY /*GENERATED BY DEFAULT AS IDENTITY*/,
    user_id bigint NOT NULL REFERENCES public.users(id) /*ON DELETE CASCADE*/,
    kind varchar(50) NOT NULL CHECK (kind IN ('S_SKILLS','HOBBY')),
    value varchar(65535) NOT NULL,
    valid_from_date date,
    valid_to_date date,
    deleted boolean DEFAULT FALSE NOT NULL,
    version bigint
);
CREATE INDEX ix_user_add_info ON public.user_add_info (user_id, kind, valid_from_date, valid_to_date);

COMMENT ON TABLE public.user_add_info is 'Любая дополнительная информация о пользователе.';
COMMENT ON COLUMN public.user_add_info.id is 'Первичный ключ.';
COMMENT ON COLUMN public.user_add_info.user_id is 'Идентификатор пользователя. Ссылка на users.id.';
COMMENT ON COLUMN public.user_add_info.kind is 'Тип. S_SKILLS - софт скилы, HOBBY - хобби. Можно добавлять новые типы по необходимости.';
COMMENT ON COLUMN public.user_add_info.value is 'Собственно сама информация.';
COMMENT ON COLUMN public.user_add_info.valid_from_date is 'Историчность. "Дата действия с".';
COMMENT ON COLUMN public.user_add_info.valid_from_date is 'Историчность. "Дата действия по".';
COMMENT ON COLUMN public.user_add_info.deleted is 'Признак soft delete.';
COMMENT ON COLUMN public.user_add_info.version is 'Версия строки. Для оптимистической блокировки.';

-- rollback DROP TABLE IF EXISTS public.user_add_info;